### ISSUE TITLE
Signing fails on non-existing folder hierarchy

### ISSUE THREAD

**Issue by rendertom** [codearoni/zxp-sign-cmd#7]
Signing operation fails if "output" destination contains non-existing nested folder hierarchy:

Works: "existingFolder/NonExistingFolder/file.zxp"
Fails: "existingFolder/NonExistingFolder1/NonExistingFolder 2/file.zxp"

Would be great if it recursively create folder hierarchy before placing a ZXP file.

**Comment by codearoni** [comment]
node 10 supports recursive mkdir natively.

I will consider adding that functionality in a future release that deprecates node 8 or lower

**Comment by codearoni** [comment]
nice bruno 👍

**Comment by codearoni** [comment]
@rendertom Recursive folder building is fixed in v2
