### ISSUE TITLE
Command fails with path with spaces

### ISSUE THREAD

**Issue by adriendurepaire** [codearoni/zxp-sign-cmd#9]
Hi,

Thanks for this useful wrapper!
When `input` or `output` path contains spaces, command fails for all methods.

**Comment by codearoni** [comment]
Odd. I could've sworn this was fixed, but turns out that was in zxp-provider underneath this module. I'll file something for it.

**Comment by ANovitsky** [comment]
Not fixed yet?

**Comment by codearoni** [comment]
@ANovitsky This should be resolved in v2. 

CC: @adriendurepaire, let me know if this continues to be an issue
